### PR TITLE
Add a test lane script

### PR DESCRIPTION
**Pull request by brybacki**
Signed-off-by: Bartosz Rybacki <brybacki@redhat.com>

**What this PR does / why we need it**:
The script has any environment variables needed for given test lane.
CI automation can just execute this, does not need to know anything
about variables.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Created https://github.com/kubevirt/project-infra/pull/2291 to use the golang builder for the functional test lane. Right now it is failing on missing golang

**Comment by brybacki** [comment]
> Created [kubevirt/project-infra#2291](https://github.com/kubevirt/project-infra/pull/2291) to use the golang builder for the functional test lane. Right now it is failing on missing golang

i have already created and tested this
https://github.com/kubevirt/project-infra/pull/2280

**Comment by awels** [comment]
not sure if your hash is correct for the golang builder, mine updates it to the latest available.

**Comment by brybacki** [comment]
;)

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Comment by brybacki** [comment]
we also need this:
 https://github.com/kubevirt/project-infra/pull/2280 so the test lane does not fail

**Comment by davidvossel** [comment]
i had to force merge this because the e2e lane is not passing. We're merging https://github.com/kubevirt/project-infra/pull/2280 now, hopefully e2e will work after this.

**Pull request merged**
