### PR TITLE
Add script for E2E CI test, to check split cluster

### PR DESCRIPTION
**Pull request by nunnatsa**
Signed-off-by: Nahshon Unna-Tsameret <nunnatsa@redhat.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by brybacki** [comment]
That was easy ;), what about a test lane for that? Is there a PR already open?

**Comment by nunnatsa** [comment]
> That was easy ;), what about a test lane for that? Is there a PR already open?

I'll open a PR right after this one will be merged.

**Review by davidvossel — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
