### PR TITLE
Get storage class from PVC for snapshot matching

### PR DESCRIPTION
**Pull request by awels**
**What this PR does / why we need it**:
Instead of using the PV to get the storage class use the PVC storage class instead. If it is nil then k8s version is < 1.28 and we return an error indicating we cannot determine the storage class name.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by davidvossel — COMMENTED** [review]
does the PV rbac need to be removed during the deploy steps for install now?

**Comment by awels** [comment]
Good point removed.

**Review by davidvossel — COMMENTED** [review]
/lgtm
/approve

**Review by davidvossel — COMMENTED** [review]
/hold

**Pull request merged**
