### PR TITLE
Option to use the default infra storageclass automatically

### PR DESCRIPTION
**Pull request by davidvossel**
With the `useDefaultInfraStorageClass` parameter, a storageclass can be created in the guest cluster without having knowledge of what the underlying infra cluster provides. Whatever is the default storageclass on the infra will be used. 

```release-note
NONE
```

### CODE REVIEW

**Comment by awels** [comment]
Is this for the 'regular' installation where the controller exists in tenant cluster? Or also for the 'split' configuration? I thought in the split configuration the tenant didn't know anything about the infra storage class already.

**Comment by davidvossel** [comment]
> Is this for the 'regular' installation where the controller exists in tenant cluster? Or also for the 'split' configuration? I thought in the split configuration the tenant didn't know anything about the infra storage class already.

it would be used for either. the storageclass in the guest wouldn't specify an infra storageclass, and the csi controller would create a PVC without the storageclass as well, which would result in the default storageclass being used. 

basically, defaults all the way down.

**Comment by davidvossel** [comment]
/hold 

I want to build of isaac's work here, https://github.com/kubevirt/csi-driver/pull/62, before merging this. We're working in similar areas and I think i can converge some of my work into his storageclass enforcement config options

**Comment by davidvossel** [comment]
obsoleted by https://github.com/kubevirt/csi-driver/pull/73

**Pull request closed without merging**
